### PR TITLE
Return avatar ID in user API response

### PR DESCRIPTION
**Pull request by FurryEli**
I need this value for a project I'm working on—plus, I think it would be useful for others working with the API.

Thanks!

### CODE REVIEW

**Comment by FurryEli** [comment]
Any updates on this?

**Comment by FurryEli** [comment]
Hey @zwagoth, just wanted to check on this again

**Comment by kiranoot** [comment]
Been in for about a week.

**Comment by tjhorner** [comment]
Oh awesome, thanks!

**Pull request closed without merging**
