### PR TITLE
[PostVersions] Allow searching for only uploads 

### PR DESCRIPTION
**Pull request by DonovanDMC**
This pr add an option for searching post versions by their version number, allowing for example, searching exclusively for uploads.

### CODE REVIEW

**Comment by Earlopain** [comment]
Is there actually a use-case for anything other than `version == 1` and `version != 1`? If not, I would prefer this to simply be combined into a select menu.

**Comment by DonovanDMC** [comment]
> Is there actually a use-case for anything other than `version == 1` and `version != 1`? If not, I would prefer this to simply be combined into a select menu.

None I can think of, no. I can do that.

**Comment by DonovanDMC** [comment]
Changed to a dropdown of `Included`, `Excluded`, `Only`, with included being the default

Should exclude uploads be kept in the background for backwards compatibility?

**Comment by Earlopain** [comment]
Eh, seems fine to just drop. I changed this to include a blank since it would otherwise always be part of the url when searching unrelated things. Already happened for the checkbox but now it can be avoided very easily.

**Comment by DonovanDMC** [comment]
> Eh, seems fine to just drop. I changed this to include a blank since it would otherwise always be part of the url when searching unrelated things. Already happened for the checkbox but now it can be avoided very easily.

Right, hadn't thought of that.

**Comment by faucetlol** [comment]
The "Included" option is now redundant to the blank line, is it not?

**Comment by Earlopain** [comment]
Sure, but that's how most things do it. Especially the order fields often contain their default values as an explicit entry.

**Comment by DonovanDMC** [comment]
> The "Included" option is now redundant to the blank line, is it not?

Not including it also could make it seem like it isn't an option, and it's hard to actually click that blank line

**Pull request merged**
