### PR TITLE
[Misc] External favicon tweaks

### PR DESCRIPTION
**Pull request by Sindrake**
Let's be honest here, there was no chance that the list added in #610 would have been comprehensive and issue-free.
This pull request addresses a couple of issues that became immediately apparent.

### Additions

| icon | domain | posts |
| :---: | --- | --- |
| blogspot com | [blogpost.com](https://e621.net/posts?tags=source:*blogspot.com*) | 3000 |
| fandom com | [fandom.com](https://e621.net/posts?tags=~source:*wikia*+~source:*fandom.com*) | 650 |
| f-list net | [f-list.net](https://e621.net/posts?tags=source:*f-list.net*) | 400 |
| furbooru org | [furbooru.org](https://e621.net/posts?tags=source:*furbooru.org*) | 250 |
| nijie info | [nijie.info](https://e621.net/posts?tags=source:*nijie.info*) | 1100 |
| yiff life | [yiff.life](https://e621.net/posts?tags=source:*yiff.life*) | 450 |
| wikimedia org | [wikimedia.org](https://e621.net/posts?tags=source:*wikimedia.org*) | 850 |
| wordpress com | [wordpress.com](https://e621.net/posts?tags=source:*wordpress.com*) | 250 |

### Aliases

|   From |   To   | Reason |
|               ---              |               ---              |            ---             |
| `exhentai.org`           | `e-hentai.org`          | alternate name    |
| `curiouscat.live`        | `curiouscat.me`        | alternate name    |
| `pillowfort.io`           | `pillowfort.social`      | redirect                |
| `subscribestar.com` | `subscribestar.adult` | redirect                |
| `wikia.com`              | `fandom.com`           | redirect                |
| `youtu.be`                |  `youtube.com`         | link shortener      |
|                                 |                                  |                             |
| `cohostcdn.org`       | `cohost.org`              | CDN                    |
| `furrycdn.org`          | `furbooru.org`           | CDN                    |
| `patreonusercontent.com` | `patreon.com` | CDN                   |
| `sofurryfiles.com`     | `sofurrt.com`             | CDN                    |
| `static.wikia.nocookie.net` | `fandom.com` | CDN                     |

#### ArchiveOfOurOwn domain was incorrect.
Previously, the link helper listed [archiveofourown.com](https://archiveofourown.com/) as the domain for AO3. That is incorrect – no posts were sourced from it, as the .com domain simply redirects to [archiveofourown.org](https://archiveofourown.org/).

That had been fixed, and the .com domain had been added as an alias – just in case.

#### Mastodon.social
A number of mastodon instances don't have unique favicons, as they just use the original one from mastodon.social.
For some reason, I used the icon sourced form baraag.com for that purpose, and did not include mastodon.social at all, despite [almost 600 posts](https://e621.net/posts?tags=source:*mastodon.social*) being sourced from it.

The `baraag.com.png` had been renamed to `mastodon.social.png`, and the link helper had been updated accordingly.

### CODE REVIEW

**Comment by Earlopain** [comment]
I've also noticed "patreonusercontent.com" => "patreon.com", which is an easy alias for patreon.

Also, isn't t.co a link shortener? As in, that can redirect to anything. I don't think that should the icon for telegram. You've called `youtu.be` a link shortener as well, but doesn't that just redirect to the longer format of youtube links?

**Comment by faucetlol** [comment]
I also don't think URL shorteners should have icons (with the exception of single-purpose ones like youtu.be) but most importantly t.co is **Twitter's** URL shortener. It definitely shouldn't get a Telegram icon.

Ideally, URL shorteners shouldn't be used as sources at all, but that's not exactly relevant to this PR.

**Comment by Sindrake** [comment]
Well, that's silly of me.
I'm not sure what happened there.

**Comment by Sindrake** [comment]
> Ideally, URL shorteners shouldn't be used as sources at all, but that's not exactly relevant to this PR.

I agree that shorteners **shouldn't** be used as sources, but it's a simple reality of the situation that they **are** used as sources.
I've removed `t.co`, since it only been used 48 times as a source. Comparatively, `youtu.be` had been used almost 500 times.

**Comment by Earlopain** [comment]
Nice PR number you've got there

**Comment by Sindrake** [comment]
I wish I got to use it for something actually interesting, not minor fixes.
Oh well.

**Pull request merged**
